### ISSUE TITLE
Error "The system cannot find the file specified" from jsreport.Local.Internal.BinaryProcess.InnerExecute()

### ISSUE THREAD

**Issue by ggmathewtor** [jsreport/jsreport-dotnet-binary#1]
I noticed "jsreport.exe" disappears from temp directory (jsreport\temp\dotnet\binary-default-1.10.0.0) after some period of time. Once it disappears all my reports failing with error "The system cannot find the file specified". Application is still in development/research mode, so this is happening on Visual Studio, not sure this will be the case once it is deployed onto IIS. I had to restart my application in order to get 'jsreport.exe' back in the temp directory.

Startup configuration;
```
            services.AddJsReport(
                new LocalReporting()
                    .Configure(c => {
                        c.TempDirectory = Path.Combine(Directory.GetCurrentDirectory(), "jsreport", "temp");
                        return c; })
                    .UseBinary(JsReportBinary.GetBinary())
                    .AsUtility()
                    .Create()
                );
```

Controller;
```
        [HttpGet("DownloadInvoice"), MiddlewareFilter(typeof(JsReportPipeline))]
        public async Task<IActionResult> DownloadInvoice(int id)
        {
            Invoice invoice = await GetInvoiceAsync(id);
            HttpContext.JsReportFeature().Recipe(Recipe.PhantomPdf);
            return View("Invoice", invoice);
        }

```
Please help

**Comment by pofider** [comment]
Interesting. 
Can you give an estimate after how long the `jsreport.exe` gets deleted?
I'm not able to replicate it and I don't think we would do such thing.

Don't you have some kind of antivirus running? 
Perhaps you could try to disable it and try it again?

**Comment by ggmathewtor** [comment]
It appears that Windows Defender is deleting the file. I even copied jsreport.exe onto a separate folder and found that the file disappeared. 

Sorry for the false alarm. Thank you Jan for your time. Please let me know if you want me to close the ticket.
