### ISSUE TITLE
jsreport.exe is marked as trojana at virustotal.com

### ISSUE THREAD

**Issue by julianortlieb** [jsreport/jsreport-dotnet-binary#4]
Hi,

I find out that jsreport.exe in the binary folder is marked as a trojana at virustotal.com
The result of the check is here: [Result](https://www.virustotal.com/gui/file/dc6c2038cc07a569e532e9e2494ab5ed5885e5005c4a44404320255e6495b4c5)

Can you please update the jsreport version from 3.11 to the newest version?
The newest version doesn't have this issue.

Kind regards

**Comment by pofider** [comment]
Thanks, the nuget with 3.13.0 was just uploaded.
